pipeline {
	environment {
EMAIL_TO = '20ne1a05g8@gmail.com'
EMAIL_FROM = 'abhishekvanama@yahoo.com'
}
	
	
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
            }
        }
        
        
        stage('ExecuteSonarQubeReport'){
            steps{
                bat  "mvn clean sonar:sonar"
            }
        }    
	       
	    
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                bat '/jenkins/scripts/deliver.sh'
            }
        }
    }
    
    post{
	
always{
 emailext to: "${EMAIL_TO}",
	  from: "${EMAIL_FROM}",
          subject: "Changed Pipeline Build is over .. Build # is ..${env.BUILD_NUMBER} and Build status is.. ${currentBuild.result}.",
          body: "Changed Pipeline Build is over .. Build # is ..${env.BUILD_NUMBER} and Build status is.. ${currentBuild.result}."
/* 	,
          replyTo: "${EMAIL_TO}" */
 }
/* 
success{
 emailext to: '20ne1a05g8@gmail.com',
          subject: "Pipeline Build is over .. Build # is ..${env.BUILD_NUMBER} and Build status is.. ${currentBuild.result}.",
          body: "Pipeline Build is over .. Build # is ..${env.BUILD_NUMBER} and Build status is.. ${currentBuild.result}.",
          replyTo: '20ne1a05g8@gmail.com'
 }
 
 failure{
 emailext to: '20ne1a05g8@gmail.com',
          subject: "Pipeline Build is over .. Build # is ..${env.BUILD_NUMBER} and Build status is.. ${currentBuild.result}.",
          body: "Pipeline Build is over .. Build # is ..${env.BUILD_NUMBER} and Build status is.. ${currentBuild.result}.",
          replyTo: '20ne1a05g8@gmail.com'
 }*/
 
}
    
    
}
